export const WORDS_ENG = [

	//3
	{name: 'cat', desc: 'A small animal with fur, four legs, a tail, and claws, usually kept as a pet or for catching mice'},
	{name: 'dog', desc: 'A common animal with four legs, especially kept by people as a pet or to hunt or guard things'},
	{name: 'arm', desc: 'Either of the two long parts of the upper body that are attached to the shoulders and have the hands at the end'},
	{name: 'leg', desc: 'One of the parts of the body of a human or animal that is used for standing or walking'},
	{name: 'cow', desc: 'A large female farm animal kept to produce meat and milk'},
	{name: 'day', desc: 'A period of 24 hours'},
	{name: 'box', desc: 'A square or rectangular container with stiff sides and sometimes a lid'},
	{name: 'key', desc: 'A piece of metal that has been cut into a special shape and is used for opening or closing a lock, starting a car engine, etc.'},
	{name: 'god', desc: 'A spirit or being believed to control some part of the universe or life and often worshipped for doing so, or something that represents this spirit or being'},
	{name: 'car', desc: 'A road vehicle with an engine, four wheels, and seats for a small number of people'},
	{name: 'bus', desc: 'A large vehicle in which people are driven from one place to another'},
	{name: 'pig', desc: 'A large pink, brown, or black farm animal with short legs and a curved tail'},
	{name: 'owl', desc: 'A bird with a flat face and large eyes that hunts small mammals at night'},
	{name: 'boy', desc: 'A male child or, more generally, a male of any age'},
	{name: 'man', desc: 'An adult male human being'},
	{name: 'nut', desc: 'The dry fruit of particular trees that grows in a hard shell and can often be eaten'},
	{name: 'eye', desc: 'One of the two organs in your face that are used for seeing'},
	{name: 'age', desc: 'The period of time someone has been alive or something has existed'},

	// 4
	{name: 'home', desc: ''},
	{name: 'head', desc: ''},
	{name: 'code', desc: ''},
	{name: 'duck', desc: ''},
	{name: 'wood', desc: ''},
	{name: 'note', desc: ''},
	{name: 'book', desc: ''},
	{name: 'corn', desc: ''},
	{name: 'plum', desc: ''},
	{name: 'lion', desc: ''},
	{name: 'swan', desc: ''},
	{name: 'girl', desc: ''},
	{name: 'goat', desc: ''},
	{name: 'yard', desc: ''},
	{name: 'roof', desc: ''},
	{name: 'zone', desc: ''},
	{name: 'area', desc: ''},
	{name: 'fall', desc: ''},
	{name: 'fish', desc: ''},
	{name: 'hero', desc: ''},
	{name: 'star', desc: ''},
	{name: 'neck', desc: ''},
	{name: 'rain', desc: ''},
	{name: 'pine', desc: ''},
	{name: 'tree', desc: ''},
	{name: 'ship', desc: ''},
	{name: 'iron', desc: ''},
	{name: 'life', desc: ''},
	{name: 'ache', desc: ''},
	{name: 'gold', desc: ''},
	{name: 'foot', desc: ''},
	{name: 'wall', desc: ''},
	{name: 'face', desc: ''},

	// 5
	{name: 'light', desc: ''},
	{name: 'night', desc: ''},
	{name: 'mouse', desc: ''},
	{name: 'phone', desc: ''},
	{name: 'hotel', desc: ''},
	{name: 'stone', desc: ''},
	{name: 'table', desc: ''},
	{name: 'beach', desc: ''},
	{name: 'color', desc: ''},
	{name: 'apple', desc: ''},
	{name: 'raven', desc: ''},
	{name: 'eagle', desc: ''},
	{name: 'woman', desc: ''},
	{name: 'grass', desc: ''},
	{name: 'floor', desc: ''},
	{name: 'water', desc: ''},
	{name: 'horse', desc: ''},
	{name: 'cloud', desc: ''},
	{name: 'sword', desc: ''},
	{name: 'brain', desc: ''},

	// 6
	{name: 'forest', desc: ''},
	{name: 'ginger', desc: ''},
	{name: 'donkey', desc: ''},
	{name: 'desert', desc: ''},
	{name: 'flower', desc: ''},
	{name: 'friend', desc: ''},
	{name: 'hunter', desc: ''},
	{name: 'letter', desc: ''},
	{name: 'monkey', desc: ''},
	{name: 'pocket', desc: ''},
	{name: 'border', desc: ''},
	{name: 'master', desc: ''},
	{name: 'health', desc: ''},
	{name: 'lizard', desc: ''},

	// 7
	{name: 'printer', desc: 'A machine that is connected to a computer and prints onto paper using ink'},
	{name: 'success', desc: 'Something that achieves positive results'},
	{name: 'cartoon', desc: 'A drawing, especially in a newspaper or magazine, that tells a joke or makes a humorous political criticism'},
	{name: 'cabbage', desc: 'A large, round vegetable with large green, white, or purple leaves that can be eaten cooked or uncooked'},
	{name: 'pumpkin', desc: 'A large, round vegetable with hard, yellow or orange flesh'},
	{name: 'hamster', desc: 'A small animal covered in fur with a short tail and large spaces in each side of its mouth for storing food. Hamsters are often kept as pets.'},
	{name: 'sparrow', desc: 'A small, grey-brown bird that is especially common in towns'},
	{name: 'journey', desc: 'The act of travelling from one place to another, especially in a vehicle'},
	{name: 'library', desc: 'A building, room, or organization that has a collection of books, documents, music, and sometimes things such as tools or artwork, for people to borrow, usually without payment'},

	// 8
	{name: 'notebook', desc: 'A book of plain paper or paper with lines, for writing on'},
	{name: 'dinosaur', desc: 'A type of reptile that became extinct about 65,000,000 years ago. There were many different types of dinosaur, some of which were extremely large.'},
	{name: 'cucumber', desc: 'A long, thin, pale green vegetable with dark green skin, usually eaten uncooked in salads'},
	{name: 'mosquito', desc: 'A small flying insect that bites people and animals and sucks their blood'},
	{name: 'location', desc: 'A place or position'},
	{name: 'headache', desc: 'A pain you feel inside your head'},
	{name: 'graffiti', desc: 'Words or drawings, especially humorous, rude, or political, on walls, doors, etc. in public places'},
	{name: 'entrance', desc: 'A door, gate, etc. by which you can enter a building or place'},
	{name: 'ellipsis', desc: 'Three dots in a printed text that show where one or more words have been intentionally left out'},

	// 9
	{name: 'judgement', desc: ''},
	{name: 'waterfall', desc: 'Water, especially from a river or stream, dropping from a higher to a lower point, sometimes from a great height'},
	{name: 'territory', desc: ''},
	{name: 'swordfish', desc: 'A large, long fish that is often eaten as food, with a very long pointed part like a beak at the front of its head'},
	{name: 'sculpture', desc: 'The art of forming solid objects that represent a thing, person, idea, etc. out of a material such as wood, clay, metal, or stone, or an object made in this way'},
	{name: 'secretary', desc: 'Someone who works in an office, writing letters, making phone calls, and arranging meetings for a person or for an organization'},
	{name: 'satellite', desc: 'A device sent up into space to travel around the earth, used for collecting information or communicating by radio, television, etc.'},
	{name: 'pineapple', desc: 'A large, juicy fruit that grows in hotter regions, having a rough skin, a short stem, and pointed leaves on the top, or its sweet, yellow flesh'},


	// 10
	{name: 'collection', desc: 'A group of objects of one type that have been collected by one person or in one place'},
	{name: 'exhibition', desc: 'An event at which objects such as paintings are shown to the public, or the act of showing these things'},
	{name: 'friendship', desc: 'A situation in which two people are friends'},
	{name: 'inquisitor', desc: 'Someone who asks a lot of questions'},
	{name: 'technology', desc: 'Technology is a particular method by which science is used for practical purposes'},

]
