export const WORDS_ENG = [

	//3
	{name: 'cat', desc: 'A small animal with fur, four legs, a tail, and claws, usually kept as a pet or for catching mice'},
	{name: 'dog', desc: 'A common animal with four legs, especially kept by people as a pet or to hunt or guard things'},
	{name: 'arm', desc: 'Either of the two long parts of the upper body that are attached to the shoulders and have the hands at the end'},
	{name: 'leg', desc: 'One of the parts of the body of a human or animal that is used for standing or walking'},
	{name: 'cow', desc: 'A large female farm animal kept to produce meat and milk'},
	{name: 'day', desc: 'A period of 24 hours'},
	{name: 'box', desc: 'A square or rectangular container with stiff sides and sometimes a lid'},
	{name: 'key', desc: 'A piece of metal that has been cut into a special shape and is used for opening or closing a lock, starting a car engine, etc.'},
	{name: 'god', desc: 'A spirit or being believed to control some part of the universe or life and often worshipped for doing so, or something that represents this spirit or being'},
	{name: 'car', desc: 'A road vehicle with an engine, four wheels, and seats for a small number of people'},
	{name: 'bus', desc: 'A large vehicle in which people are driven from one place to another'},
	{name: 'pig', desc: 'A large pink, brown, or black farm animal with short legs and a curved tail'},
	{name: 'owl', desc: 'A bird with a flat face and large eyes that hunts small mammals at night'},
	{name: 'boy', desc: 'A male child or, more generally, a male of any age'},
	{name: 'man', desc: 'An adult male human being'},
	{name: 'nut', desc: 'The dry fruit of particular trees that grows in a hard shell and can often be eaten'},
	{name: 'eye', desc: 'One of the two organs in your face that are used for seeing'},
	{name: 'age', desc: 'The period of time someone has been alive or something has existed'},
	{name: 'ant', desc: 'A very small insect that lives under the ground in large and well-organized social groups'},
	{name: 'son', desc: 'A male child in relation to his parents'},
	{name: 'ice', desc: 'Water that has frozen and become solid, or pieces of this'},
	{name: 'fog', desc: 'A weather condition in which very small drops of water come together to form a thick cloud close to the land or sea, making it difficult to see'},
	{name: 'rat', desc: 'A small rodent, larger than a mouse, that has a long tail and is considered to be harmful'},
	{name: 'ham', desc: "Pig's meat from the leg or shoulder, preserved with salt or smoke"},
	{name: 'law', desc: 'A rule, usually made by a government, that is used to order the way in which a society behaves'},
	{name: 'hat', desc: 'A covering for the head that is not part of a piece of clothing'},
	{name: 'lap', desc: 'A complete trip around a race track that is repeated several times during a competition'},

	// 4
	{name: 'home', desc: 'The house, apartment, etc. where you live, especially with your family'},
	{name: 'head', desc: 'The part of the body above the neck where the eyes, nose, mouth, ears, and brain are'},
	{name: 'code', desc: 'A language used to program computers'},
	{name: 'duck', desc: 'A bird that lives by water and has webbed feet, a short neck, and a large beak'},
	{name: 'wood', desc: 'A hard substance that forms the branches and trunks of trees and can be used as a building material, for making things, or as a fuel'},
	{name: 'note', desc: ''},
	{name: 'book', desc: ''},
	{name: 'corn', desc: ''},
	{name: 'plum', desc: ''},
	{name: 'lion', desc: ''},
	{name: 'swan', desc: ''},
	{name: 'girl', desc: ''},
	{name: 'goat', desc: ''},
	{name: 'yard', desc: ''},
	{name: 'roof', desc: ''},
	{name: 'zone', desc: ''},
	{name: 'area', desc: ''},
	{name: 'fall', desc: ''},
	{name: 'fish', desc: ''},
	{name: 'hero', desc: ''},
	{name: 'star', desc: ''},
	{name: 'neck', desc: ''},
	{name: 'rain', desc: ''},
	{name: 'pine', desc: ''},
	{name: 'tree', desc: ''},
	{name: 'ship', desc: ''},
	{name: 'iron', desc: ''},
	{name: 'life', desc: ''},
	{name: 'ache', desc: 'A continuous pain that is unpleasant but not very strong'},
	{name: 'gold', desc: 'A chemical element that is a valuable, shiny, yellow metal used to make coins and jewellery'},
	{name: 'foot', desc: 'The part of the body at the bottom of the leg on which a person or animal stands'},
	{name: 'wall', desc: 'A vertical structure, often made of stone or brick, that divides or surrounds something'},
	{name: 'face', desc: 'The front of the head, where the eyes, nose, and mouth are'},
	{name: 'tail', desc: "A part of an animal's body, sticking out from the base of the back, or something similar in shape or position"},
	{name: 'lake', desc: 'A large area of water surrounded by land and not connected to the sea except by rivers or streams'},
	{name: 'gate', desc: 'A part of a fence or outside wall that is fixed at one side and opens and closes like a door, usually made of metal or wooden strips'},
	{name: 'salt', desc: 'A common white substance found in sea water and in the ground, used especially to add flavour to food or to preserve it'},
	{name: 'fuel', desc: 'A substance that is used to provide heat or power, usually by being burned'},
	{name: 'road', desc: 'A long, hard surface built for vehicles to travel along'},
	{name: 'pain', desc: 'A feeling of physical suffering caused by injury or illness'},
	{name: 'nest', desc: 'A structure built by birds or insects to leave their eggs in to develop, and by some other animals to give birth or live in'},
	{name: 'cake', desc: 'A sweet food made with a mixture of flour, eggs, fat, and sugar'},
	{name: 'rope', desc: 'Strong, thick string made of long twisted threads'},
	{name: 'pipe', desc: 'A tube inside which liquid or gas flows from one place to another'},

	// 5
	{name: 'light', desc: 'The brightness that comes from the sun, fire, etc. and from electrical devices'},
	{name: 'night', desc: 'The part of every 24-hour period when it is dark because there is very little light from the sun'},
	{name: 'mouse', desc: 'A small mammal with short fur, a pointed face, and a long tail'},
	{name: 'phone', desc: 'A device that uses either a system of wires along which electrical signals are sent or a system of radio signals to make it possible for you to speak to someone in another place who has a similar device'},
	{name: 'hotel', desc: 'A building where you pay to have a room to sleep in, and where you can sometimes eat meals'},
	{name: 'stone', desc: 'The hard, solid substance found in the ground that is often used for building'},
	{name: 'table', desc: 'A flat surface, usually supported by four legs, used for putting things on'},
	{name: 'beach', desc: 'An area of sand or small stones near the sea or another area of water such as a lake'},
	{name: 'apple', desc: 'A round fruit with firm, white flesh and a green, red, or yellow skin'},
	{name: 'raven', desc: 'The largest bird in the crow family, with shiny black feathers'},
	{name: 'eagle', desc: 'A large, strong bird with a curved beak that eats meat and can see very well'},
	{name: 'woman', desc: 'An adult female human being'},
	{name: 'grass', desc: 'A type of plant with narrow leaves growing from the base.'},
	{name: 'floor', desc: 'The flat surface of a room on which you walk'},
	{name: 'water', desc: 'A clear liquid, without colour or taste, that falls from the sky as rain and is necessary for animal and plant life'},
	{name: 'horse', desc: 'A large animal with four legs that people ride on or use for carrying things or pulling vehicles'},
	{name: 'cloud', desc: 'A grey or white mass in the sky, made up of very small floating drops of water'},
	{name: 'sword', desc: 'A weapon with a long, sharp metal blade and a handle, used especially in the past'},
	{name: 'brain', desc: 'Tthe organ inside the head that controls thought, memory, feelings, and activity'},
	{name: 'sugar', desc: 'A sweet substance especially from the plants sugar cane and sugar beet, used to make food and drinks sweet'},
	{name: 'heart', desc: 'The organ in your chest that sends the blood around your body'},
	{name: 'paper', desc: 'Thin, flat material made from crushed wood or cloth, used for writing, printing, or drawing on'},
	{name: 'snake', desc: 'A reptile with a long body and no legs'},
	{name: 'space', desc: "The empty area outside Earth's atmosphere, where the planets and the stars are"},
	{name: 'swamp', desc: 'Very wet, soft land'},
	{name: 'shape', desc: 'The particular physical form or appearance of something'},

	// 6
	{name: 'forest', desc: 'A large area of land covered with trees and plants, usually larger than a wood, or the trees and plants themselves'},
	{name: 'ginger', desc: 'The spicy root of a tropical plant that is used in cooking or preserved in sugar, or a powder made from this root, used as a spice'},
	{name: 'donkey', desc: 'An animal like a small horse with long ears'},
	{name: 'desert', desc: 'An area, often covered with sand or rocks, where there is very little rain and not many plants'},
	{name: 'flower', desc: 'The part of a plant that is often brightly coloured and has a pleasant smell, or the type of plant that produces these'},
	{name: 'friend', desc: 'A person who you know well and who you like a lot, but who is usually not a member of your family'},
	{name: 'hunter', desc: 'A person or an animal that hunts animals for food or for sport'},
	{name: 'letter', desc: 'A written message from one person to another, usually put in an envelope and sent by post'},
	{name: 'monkey', desc: 'An animal that lives in hot countries, has a long tail, and climbs trees.'},
	{name: 'pocket', desc: 'A small bag for carrying things in, made of cloth and sewn into the inside or onto the outside of a piece of clothing'},
	{name: 'border', desc: 'A line that has been agreed to divide one country from another'},
	{name: 'master', desc: 'A person who is very skilled in a particular job or activity'},
	{name: 'health', desc: 'The condition of the body and the degree to which it is free from illness, or the state of being well'},
	{name: 'lizard', desc: 'A small reptile that has a long body, four short legs, a long tail, and thick skin'},
	{name: 'shadow', desc: 'An area of darkness, caused by light being blocked by something'},

	// 7
	{name: 'printer', desc: 'A machine that is connected to a computer and prints onto paper using ink'},
	{name: 'success', desc: 'Something that achieves positive results'},
	{name: 'cartoon', desc: 'A drawing, especially in a newspaper or magazine, that tells a joke or makes a humorous political criticism'},
	{name: 'cabbage', desc: 'A large, round vegetable with large green, white, or purple leaves that can be eaten cooked or uncooked'},
	{name: 'pumpkin', desc: 'A large, round vegetable with hard, yellow or orange flesh'},
	{name: 'hamster', desc: 'A small animal covered in fur with a short tail and large spaces in each side of its mouth for storing food. Hamsters are often kept as pets.'},
	{name: 'sparrow', desc: 'A small, grey-brown bird that is especially common in towns'},
	{name: 'journey', desc: 'The act of travelling from one place to another, especially in a vehicle'},
	{name: 'library', desc: 'A building, room, or organization that has a collection of books, documents, music, and sometimes things such as tools or artwork, for people to borrow, usually without payment'},
	{name: 'weather', desc: 'The conditions in the air above the earth such as wind, rain, or temperature, especially at a particular time over a particular area'},

	// 8
	{name: 'notebook', desc: 'A book of plain paper or paper with lines, for writing on'},
	{name: 'dinosaur', desc: 'A type of reptile that became extinct about 65,000,000 years ago. There were many different types of dinosaur, some of which were extremely large.'},
	{name: 'cucumber', desc: 'A long, thin, pale green vegetable with dark green skin, usually eaten uncooked in salads'},
	{name: 'mosquito', desc: 'A small flying insect that bites people and animals and sucks their blood'},
	{name: 'location', desc: 'A place or position'},
	{name: 'headache', desc: 'A pain you feel inside your head'},
	{name: 'graffiti', desc: 'Words or drawings, especially humorous, rude, or political, on walls, doors, etc. in public places'},
	{name: 'entrance', desc: 'A door, gate, etc. by which you can enter a building or place'},
	{name: 'ellipsis', desc: 'Three dots in a printed text that show where one or more words have been intentionally left out'},
	{name: 'hospital', desc: 'A place where people who are ill or injured are treated and taken care of by doctors and nurses'},

	// 9
	{name: 'judgement', desc: ''},
	{name: 'waterfall', desc: 'Water, especially from a river or stream, dropping from a higher to a lower point, sometimes from a great height'},
	{name: 'territory', desc: ''},
	{name: 'swordfish', desc: 'A large, long fish that is often eaten as food, with a very long pointed part like a beak at the front of its head'},
	{name: 'sculpture', desc: 'The art of forming solid objects that represent a thing, person, idea, etc. out of a material such as wood, clay, metal, or stone, or an object made in this way'},
	{name: 'secretary', desc: 'Someone who works in an office, writing letters, making phone calls, and arranging meetings for a person or for an organization'},
	{name: 'satellite', desc: 'A device sent up into space to travel around the earth, used for collecting information or communicating by radio, television, etc.'},
	{name: 'pineapple', desc: 'A large, juicy fruit that grows in hotter regions, having a rough skin, a short stem, and pointed leaves on the top, or its sweet, yellow flesh'},


	// 10
	{name: 'collection', desc: 'A group of objects of one type that have been collected by one person or in one place'},
	{name: 'exhibition', desc: 'An event at which objects such as paintings are shown to the public, or the act of showing these things'},
	{name: 'friendship', desc: 'A situation in which two people are friends'},
	{name: 'inquisitor', desc: 'Someone who asks a lot of questions'},
	{name: 'technology', desc: 'Technology is a particular method by which science is used for practical purposes'},

]
